DROP TABLE IF EXISTS AUTHORS CASCADE;
DROP TABLE IF EXISTS BOOKS CASCADE;
DROP TABLE IF EXISTS BOT_USERS CASCADE;

CREATE TABLE AUTHORS (ID SERIAL PRIMARY KEY, NAME VARCHAR(255) NOT NULL);
CREATE TABLE BOOKS (
	ID SERIAL PRIMARY KEY,
	TITLE VARCHAR(255) NOT NULL,
	AUTHOR_ID INTEGER REFERENCES AUTHORS (ID) ON DELETE CASCADE,
	AVAILABLE_COPIES INTEGER CHECK (AVAILABLE_COPIES >= 0)
);
CREATE TABLE BOT_USERS (
	TELEGRAM_ID BIGINT PRIMARY KEY,
	FULL_NAME VARCHAR(255),
	JOINED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
INSERT INTO
	AUTHORS (NAME)
VALUES
	('bitta bro'),
	('Kimdir'),
	('Depressed Expresso');
INSERT INTO
	BOOKS (TITLE, AUTHOR_ID, AVAILABLE_COPIES)
VALUES
	('XAMSA', 1, 5),
	('SAMSA', 1, 2),
	('SOAT', 2, 4),
	('Bobir nomi', 2, 0),
	('Bekzod aka ( depressing story )', 3, 7);